"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": false

files:
  - source: "/core/src/main/resources/lang/en_US.json"
    translation: "/core/src/main/resources/lang/%locale_with_underscore%.json"
  - source: "/assets/NON-DEV/README.md"
    translation: "/assets/NON-DEV/README_%locale_with_underscore%.md"
